services:
  runner:
    image: sousadax/github-actions:latest # You can use this image or build your own
    restart: always
    platform: linux/amd64
    build:
      context: "Docker Image"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M