services:
  runner:
    image: sousadax/github-actions:latest # You can use this image or build your own
    restart: always
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: "Docker Image"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4